version: '3'

services:
  backend:
    build:
      context: ./backend
    expose:
      - "3001"
    networks: 
      - node-network
      
  frontend:
    build:
      context: ./frontend
    expose:
      - "3000"
    depends_on:
      - backend
    networks: 
      - node-network

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
    networks: 
      - node-network

networks:
  node-network:
    driver: bridge