version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - nginx

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - backend


# version: '3'

# services:
#   backend:
#     build:
#       context: ./backend
#     ports:
#       - "3001:3001"
#     networks: 
#       - node-network
      
#   frontend:
#     build:
#       context: ./frontend
#     ports:
#       - "3000:3000"
#     depends_on:
#       - backend
#     networks: 
#       - node-network

#   nginx:
#     build:
#       context: ./nginx
#     ports:
#       - "5000:80"
#     depends_on:
#       - frontend
#       - backend
#     networks: 
#       - node-network

# networks:
#   node-network:
#     driver: bridge

